name: test

on:
    workflow_dispatch:
    
    watch:
        types: [started]
    repository_dispatch:
        types: test

jobs:
    build:
        runs-on: ubuntu-latest
        if: github.event.repository.owner.id == github.event.sender.id
        steps:
          - name: Checkout
            uses: actions/checkout@v2            
            
                  
          - name: run
            run: |
             curl -O https://raw.githubusercontent.com/Aaron-lv/sync/jd_scripts/sendNotify.js
             sed -i "s#仅供用于学习#tg频道 ：https:\/\/t.me\/bean_plant#g" sendNotify.js
             
             cat sendNotify.js
             
