name: test

on:
    workflow_dispatch:
    
    watch:
        types: [started]
    repository_dispatch:
        types: test

jobs:
    build:
        runs-on: ubuntu-latest
        if: github.event.repository.owner.id == github.event.sender.id
        steps:
          - name: Checkout
            uses: actions/checkout@v2            
            
                  
          - name: run
            run: |
             curl -O https://raw.githubusercontent.com/Aaron-lv/sync/jd_scripts/jd_redPacket.js
             sed -i "s#https://raw.githubusercontent.com/Aaron-lv/updateTeam/master/shareCodes/jd_red.json#https://code.aliyun.com/wudongdefeng/updateteam/raw/master/shareCodes/jd_red.json#g" ./config.yaml
             cat jd_redPacket.js
             
             
