name: test

on:
    workflow_dispatch:
    
    watch:
        types: [started]
    repository_dispatch:
        types: test

jobs:
    build:
        runs-on: ubuntu-latest
        if: github.event.repository.owner.id == github.event.sender.id
        steps:
          - name: Checkout
            uses: actions/checkout@v2            
            
                  
          - name: run
            run: |
             curl -O https://raw.githubusercontent.com/smiek2221/scripts/master/gua_opencard23.js
             curl -O https://raw.githubusercontent.com/smiek2221/scripts/master/gua_opencard22.js
             sed -i "s/guaopencard_addSku[0~99]/guaopencard_addSku/g" ./gua_opencard*.js
             sed -i "s/guaopencard[0~99]/guaopencard/g" ./gua_opencard*.js
             
             cat gua_opencard23.js
             
